on:
  push:
    branches:
      - main
    paths:
      - "content/docs/**"
      - ".github/workflows/reindex.yml"
env:
  LOCAL_URL: https://docs.nebulaproxy.io
  ALGOLIA_PRIVATE_API_KEY: ${{ secrets.ALGOLIA_PRIVATE_API_KEY }}

jobs:
  reindex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - name: Install Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Build app
        run: pnpm build
      - name: Reindex Algolia
        run: pnpm index
